<a href="https://colab.research.google.com/github/adityapandey23/TRC_ML_Bootcamp/blob/main/TRC_Numpy_day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **Learning Numpy**


---


### Introduction

*   Before using numpy in our programs we have to import it.


```
import numpy
numpy.__version__
```

or



In [ ]:
import numpy as np
np.__version__

'1.23.5'

Note:


*   Numpy array is just like normal arrays in C++ or Java
*   Numpy array is faster than python list as it doesn't have to figure out what is the data type the element is!




In [ ]:
# Converting array into a list
l = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
arr_l = np.array(l)
print("Data type of l:",type(l))
print("Data type of arr_l:",type(arr_l)) # ndarray objects

Data type of l: <class 'list'>
Data type of arr_l: <class 'numpy.ndarray'>


### Data Sets
This is the data sets we'll be working with! :)

In [ ]:
# List of cloud technologies in 2023
cloud_2023 = ['Amazon Web Services (AWS)', 'Firebase', 'Cloudflare', 'Google Cloud',
              'Digital Ocean','Heroku', 'Vercel', 'Netlify', 'VMware', 'Hetzner',
              'Linode, now Akamai', 'Managed Hosting', 'OVH','Oracle Cloud Infrastructure (OCI)',
              'OpenShift', 'Fly.io', 'Vultr', 'Render', 'OpenStack','IBM Cloud Or Watson', 'Scaleway', 'Colocation', 'Microsoft Azure']

#list of all votes for each cloud platform (Four values corresponds to one value in cloud_2023)
votes_raw=[33818, 29479, 654, 1185,10761, 8550, 628, 486,10599, 8326, 420, 621,16592,
           13304, 652, 866, 9299, 7838, 247, 393,8358, 6535, 492, 418,7431, 5727, 487,
           392,6228, 4708, 498, 330,4964, 3584, 262, 396,3069, 2465, 67, 184, 2755, 2104,
           125, 167,2379, 1889, 63, 137,2378, 1912, 76, 126,1810, 1146, 123, 190,1671, 1432, 22,
           66, 1649, 1342, 72, 79,1357, 1021, 55, 94, 1287, 920, 132, 69,1076, 802, 53, 78,801,
           571, 53, 70,628, 520, 0, 31,7, 385, 20, 30,18105, 15441, 370, 714]

print("Data type of cloud_2023 :",type(cloud_2023))
print("Data type of votes_raw :",type(votes_raw))

Data type of cloud_2023 : <class 'list'>
Data type of votes_raw : <class 'list'>


Converting list to numpy array


*   cloud_2023 - > cloud_2023_array
*   votes_raw - > votes_raw_array



In [ ]:
import numpy as np
cloud_2023_array = np.array(cloud_2023)
votes_raw_array = np.array(votes_raw)
print("Data type of cloud_2023_array is ",type(cloud_2023_array))
print("Data type of votes_raw_array is ",type(votes_raw_array))

Data type of cloud_2023_array is  <class 'numpy.ndarray'>
Data type of votes_raw_array is  <class 'numpy.ndarray'>


### Properties:

In [ ]:
print("Number of cloud services in the array",cloud_2023_array.size) # Size property
print("Shape of the array",cloud_2023_array.shape) # Shape property | (23,) -> (23,1) | (m x n)
print("Data type of each element in cloud_2023_array",cloud_2023_array.dtype) # Data type property | U33 {U means Unicode and 33 means 33 bytes}
print("Data type of each element in votes_raw_array",votes_raw_array.dtype) #  Data type property | int64
print("Number of dimensions of cloud_2023_array",cloud_2023_array.ndim) # Dimension property | Number of square brackets

Number of cloud services in the array 23
Shape of the array (23,)
Data type of each element in cloud_2023_array <U33
Data type of each element in votes_raw_array int64
Number of dimensions of cloud_2023_array 1


### Type Casting


*   We do this for better speed
*   We shouldn't overdo it otherwise we'll run into space issues



In [ ]:
votes_raw_array_32_bit = np.array(votes_raw,dtype=np.int32)
print(votes_raw_array_32_bit)

[33818 29479   654  1185 10761  8550   628   486 10599  8326   420   621
 16592 13304   652   866  9299  7838   247   393  8358  6535   492   418
  7431  5727   487   392  6228  4708   498   330  4964  3584   262   396
  3069  2465    67   184  2755  2104   125   167  2379  1889    63   137
  2378  1912    76   126  1810  1146   123   190  1671  1432    22    66
  1649  1342    72    79  1357  1021    55    94  1287   920   132    69
  1076   802    53    78   801   571    53    70   628   520     0    31
     7   385    20    30 18105 15441   370   714]


If we use 16-bit instead of 32-bit we'll run into errors for large numbers


```
votes_raw_array_16_bit = np.array(votes_raw,dtype=np.int16)
votes_raw_array_16_bit # The first number got screwed as it was too long
```


Feature:

If it's the last line and we only write simply the name then we can print it (Google Collab feature)

### Upcasting


*   Basically converting an hetrogenous list into a homogenous array


In [ ]:
test = [1, 2.6, True]
test_upcasted = np.array(test,dtype = "int")
print("The follow array is the upcasted array:")
test_upcasted

The follow array is the upcasted array:


array([1, 2, 1])

### Reshaping


*   Basically reshaping the data set according to our needs



In [ ]:
print("The shape of the votes_2023_array",votes_raw_array.shape) # current shape

The shape of the votes_2023_array (92,)


Let's start off by experimenting with only 8 value and then we'll perform the similar action in the main data set

In [ ]:
test_arr = np.array([1,2,3,4,5,6,7,8])
print(type(test_arr))

<class 'numpy.ndarray'>


We have to convert

[1,2,3,4,5,6,7,8] ->[[1,2,3,4],[5,6,7,8]]

1x8 -> 2x4

In [ ]:
reshape_test_arr = np.reshape(test_arr,(len(test_arr)//4,4))
reshape_test_arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

We have used the floor division as the place where we have to use it expects a int not a float

Now, let's do it with the main data set.

In [ ]:
merged_votes_array = np.reshape(votes_raw_array,(len(votes_raw_array)//4,4))
print("The shape of the original array",votes_raw_array.shape)
print("\n",votes_raw_array)

print("\n\n") # Looks better :p

print("The shape of the merged array",merged_votes_array.shape)
print("\n",merged_votes_array)

The shape of the original array (92,)

 [33818 29479   654  1185 10761  8550   628   486 10599  8326   420   621
 16592 13304   652   866  9299  7838   247   393  8358  6535   492   418
  7431  5727   487   392  6228  4708   498   330  4964  3584   262   396
  3069  2465    67   184  2755  2104   125   167  2379  1889    63   137
  2378  1912    76   126  1810  1146   123   190  1671  1432    22    66
  1649  1342    72    79  1357  1021    55    94  1287   920   132    69
  1076   802    53    78   801   571    53    70   628   520     0    31
     7   385    20    30 18105 15441   370   714]



The shape of the merged array (23, 4)

 [[33818 29479   654  1185]
 [10761  8550   628   486]
 [10599  8326   420   621]
 [16592 13304   652   866]
 [ 9299  7838   247   393]
 [ 8358  6535   492   418]
 [ 7431  5727   487   392]
 [ 6228  4708   498   330]
 [ 4964  3584   262   396]
 [ 3069  2465    67   184]
 [ 2755  2104   125   167]
 [ 2379  1889    63   137]
 [ 2378  1912    76   126]
 [ 18

Instead of having all this data in a single array, let's just divide the array into four parts

In [ ]:
total_votes_array = merged_votes_array[:,0]
professional_votes_array = merged_votes_array[:,1]
beginner_votes_array = merged_votes_array[:,2]
other_votes_array = merged_votes_array[:,3]

print("Total votes array:\n",total_votes_array)
print("\n\n")
print("Professional votes array:\n",professional_votes_array)
print("\n\n")
print("Beginner votes array:\n",beginner_votes_array)
print("\n\n")
print("Other votes array:\n",other_votes_array)
print("\n\n")

Total votes array:
 [33818 10761 10599 16592  9299  8358  7431  6228  4964  3069  2755  2379
  2378  1810  1671  1649  1357  1287  1076   801   628     7 18105]



Professional votes array:
 [29479  8550  8326 13304  7838  6535  5727  4708  3584  2465  2104  1889
  1912  1146  1432  1342  1021   920   802   571   520   385 15441]



Beginner votes array:
 [654 628 420 652 247 492 487 498 262  67 125  63  76 123  22  72  55 132
  53  53   0  20 370]



Other votes array:
 [1185  486  621  866  393  418  392  330  396  184  167  137  126  190
   66   79   94   69   78   70   31   30  714]





### Slicing

Let's discuss some basics about slicing in Python

In [ ]:
l = [1,2,3,4,5]
print("The first element of the list is",l[0])
print("Elements from second position to fourth position",l[1:4]) # [included:excluded]

The first element of the list is 1
Elements from second position to fourth position [2, 3, 4]


In similar fasion we can also slice numpy arrays. Let's do it

In [ ]:
# Corresponding vote values for a random cloud service
print("Cloud service name:",cloud_2023_array[:5])
print("Total number of votes:",total_votes_array[:5])
print("Profession votes",professional_votes_array[:5])
print("Beginner votes:",beginner_votes_array[:5])
print("Other votes:",other_votes_array[:5])

Cloud service name: ['Amazon Web Services (AWS)' 'Firebase' 'Cloudflare' 'Google Cloud'
 'Digital Ocean']
Total number of votes: [33818 10761 10599 16592  9299]
Profession votes [29479  8550  8326 13304  7838]
Beginner votes: [654 628 420 652 247]
Other votes: [1185  486  621  866  393]


Note:



*   If we do something like `cloud_2023_array[:4]` then we'll get the first four elements
*   Slicing and changing the values affect the numpy array meanwhile it has no affect on python list




In [ ]:
# For example
ls = [1,2,3,4,5]
ls_arr = np.array(ls)

ls[0:3][1] = 0
ls_arr[0:3][1] = 0

print("The list is",ls)
print("The array is",ls_arr)

The list is [1, 2, 3, 4, 5]
The array is [1 0 3 4 5]


But we don't want that so we'll create a copy of the slice and store it in a different variable

In [ ]:
ls_arr = np.array([1,2,3,4,5])
even_index_elements_array = ls_arr[0:5:2].copy() # This is crucial
print("Even index elements array is",even_index_elements_array)
# Now let's change something in the array and see whether those changes are refelected in the main array or not
even_index_elements_array[0] = 2
print("The original array",ls_arr)
print("The even index elements array",even_index_elements_array)
# So no changes to the original array

Even index elements array is [1 3 5]
The original array [1 2 3 4 5]
The even index elements array [2 3 5]


### Vectorization in Numpy


*   It is basically adding two arrays without the need of a manual loop in an user defined function
*   Let's see the time difference



In [ ]:
import numpy as np
def compute_non_professional_votes(beginner_votes_array,other_votes_array):
    output = np.empty(len(beginner_votes_array)) # np.empty(size) - > Declares a empty numpy array of the given size
    for i in range(len(beginner_votes_array)):
        output[i] = beginner_votes_array[i] + other_votes_array[i]
    return output

%timeit compute_non_professional_votes(beginner_votes_array,other_votes_array)
%timeit (beginner_votes_array,other_votes_array)

11.6 µs ± 3.23 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
72.8 ns ± 0.959 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


*   As we can see that using vectorized addition is way more faster than manually looping using a user defined function.
*   We will implement vectorization in numpy arrays using Ufuncs(Univesal functions)

In [ ]:
print("Original array:\n",beginner_votes_array)
print("\n\n")
print("Adding 2 to all elements:\n",beginner_votes_array+2)
# print("Adding 2 to all the elements:\n",np.add(beginner_votes_array,2)) # This will also be the same
print("\n\n")
print("Dividing all elements by 2(floor):\n",beginner_votes_array//2)

Original array:
 [654 628 420 652 247 492 487 498 262  67 125  63  76 123  22  72  55 132
  53  53   0  20 370]



Adding 2 to all elements:
 [656 630 422 654 249 494 489 500 264  69 127  65  78 125  24  74  57 134
  55  55   2  22 372]



Dividing all elements by 2(floor):
 [327 314 210 326 123 246 243 249 131  33  62  31  38  61  11  36  27  66
  26  26   0  10 185]


In [ ]:
non_professional_votes_array = beginner_votes_array + other_votes_array
non_professional_votes_array_mean = round(np.mean(non_professional_votes_array),2) # rounding off till two decimal places
print("The non professional votes array:\n",non_professional_votes_array)
print("The non professional votes array mean:\n",non_professional_votes_array_mean)

The non professional votes array:
 [1839 1114 1041 1518  640  910  879  828  658  251  292  200  202  313
   88  151  149  201  131  123   31   50 1084]
The non professional votes array mean:
 551.87


In [ ]:
non_professional_votes_array>non_professional_votes_array_mean

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True])

As we can see if we use a condition with a numpy array, the program returns a boolean array (true -> at indexes whose value satisfies the condition and false -> at indexes whose value doesn't satisfies the condition)

In [ ]:
np.sum(non_professional_votes_array>non_professional_votes_array_mean)

10

So this shows that 10 values are better than the average value.

If we pass this boolean array to different array it'll print all the places where the valuer are true!

In [ ]:
print("Dominant cloud platforms:\n",cloud_2023_array[non_professional_votes_array>1000])
# Dominant in the sense that their votes are greater than 1k

Dominant cloud platforms:
 ['Amazon Web Services (AWS)' 'Firebase' 'Cloudflare' 'Google Cloud'
 'Microsoft Azure']


In [ ]:
print("Are all cloud platforms greater than 1000 votes?\n",np.all(non_professional_votes_array>1000))

Are all cloud platforms greater than 1000 votes?
 False


This np.all(condition) function will give true only if all the values are true!

In [ ]:
print("Is there any cloud platform with more than 1000 votes?\n",np.any(non_professional_votes_array>1000))

Is there any cloud platform with more than 1000 votes?
 True


This np.any(condition) function will give true when atleast one value is true.

-> Boolean masking in NumPy refers to the process of using boolean arrays (arrays containing True and False values) to filter elements from another array. This technique allows you to extract, modify, or manipulate elements from an array based on a certain condition defined by a boolean array.

### Concatenation

In [ ]:
new_cloud_platforms = np.array(["ZohoCorpCloud","MyCloudPlatform"])
updated_cloud_2023_array = np.concatenate([cloud_2023_array,new_cloud_platforms])
print("The Updated cloud service list: \n",updated_cloud_2023_array)
print("\n")
print("The size of the Updated cloud service list: \n",updated_cloud_2023_array.size)

The Updated cloud service list: 
 ['Amazon Web Services (AWS)' 'Firebase' 'Cloudflare' 'Google Cloud'
 'Digital Ocean' 'Heroku' 'Vercel' 'Netlify' 'VMware' 'Hetzner'
 'Linode, now Akamai' 'Managed Hosting' 'OVH'
 'Oracle Cloud Infrastructure (OCI)' 'OpenShift' 'Fly.io' 'Vultr' 'Render'
 'OpenStack' 'IBM Cloud Or Watson' 'Scaleway' 'Colocation'
 'Microsoft Azure' 'ZohoCorpCloud' 'MyCloudPlatform']


The size of the Updated cloud service list: 
 25


### Some other useful stuff

`np.add.reduce(array)`
This is used to add-up all the elemnts of an array and reduce it to a single number

In [ ]:
print("Total number of voters in stack overflow",np.add.reduce(total_votes_array))
print("Total number of professional voters in stack overflow",np.add.reduce(professional_votes_array))
print("Total number of beginner voters in stack overflow",np.add.reduce(beginner_votes_array))
print("Total number of other voters in stack overflow",np.add.reduce(other_votes_array))

Total number of voters in stack overflow 147022
Total number of professional voters in stack overflow 120001
Total number of beginner voters in stack overflow 5571
Total number of other voters in stack overflow 7122


`np.min(array)` :- This function will give the minimum element from the array

`np.max(array)` :- This function will give the maximum element from the array

In [ ]:
print("The maximum number of votes:\n",np.max(total_votes_array))
print("The minimum number of votes:\n",np.min(total_votes_array))

The maximum number of votes:
 33818
The minimum number of votes:
 7


But technically we don't have any use of this as we don't know who has the value is maximum and minimum

To solve this we'll use

```
np.argmax(array) # For max index
np.argmin(array) # For min index
```



In [ ]:
max_votes_index = np.argmax(total_votes_array)
min_votes_index = np.argmin(total_votes_array)
print("The index at the maxmimum votes is present:\n",max_votes_index)
print("The index at the minimum votes is present:\n",min_votes_index)

The index at the maxmimum votes is present:
 0
The index at the minimum votes is present:
 21


To make it look better we'll use f-strings concepts from python

In [ ]:
print(f"The maximum number of votes is {cloud_2023_array[max_votes_index]} with {total_votes_array[max_votes_index]} total votes")
print(f"The minimum number of votes is {cloud_2023_array[min_votes_index]} with {total_votes_array[min_votes_index]} total votes")

The maximum number of votes is Amazon Web Services (AWS) with 33818 total votes
The minimum number of votes is Colocation with 7 total votes


Now we'll apply the logic for sorting using


```
np.sort(array)
```

this will return the sorted array

For example:

In [ ]:
total_values_sorted = np.sort(total_votes_array)
print("Sorted array of total votes\n",total_values_sorted)

Sorted array of total votes
 [    7   628   801  1076  1287  1357  1649  1671  1810  2378  2379  2755
  3069  4964  6228  7431  8358  9299 10599 10761 16592 18105 33818]


But we don't want it be sorted in terms of value, we want it to be sorted in terms of indexes and for that we'll use


```
np.argsort(array)
```

In this way we'll get an array which will contain the indexes of the array in sorted format

For example:

In [ ]:
sorted_indices_total = np.argsort(total_votes_array)
print("(Asc)Sorted array of total votes's index\n",sorted_indices_total)
print("\n\n")
# If we want it to be reverse
sorted_indices_total_dec = sorted_indices_total[::-1]
print("(Dsc)Sorted array of total votes's index\n",sorted_indices_total_dec)

(Asc)Sorted array of total votes's index
 [21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  2  1  3 22  0]



(Dsc)Sorted array of total votes's index
 [ 0 22  3  1  2  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]


This function returned an array which contains all the indexes in sorted from

In [ ]:
cloud_2023_sorted = [cloud_2023_array[i] for i in sorted_indices_total_dec]
print(cloud_2023_sorted)

['Amazon Web Services (AWS)', 'Microsoft Azure', 'Google Cloud', 'Firebase', 'Cloudflare', 'Digital Ocean', 'Heroku', 'Vercel', 'Netlify', 'VMware', 'Hetzner', 'Linode, now Akamai', 'Managed Hosting', 'OVH', 'Oracle Cloud Infrastructure (OCI)', 'OpenShift', 'Fly.io', 'Vultr', 'Render', 'OpenStack', 'IBM Cloud Or Watson', 'Scaleway', 'Colocation']


Now let's learn about partial sorting



*   Sorting is a very resource intensive task
*   If we don't need the whole array to be sorted we'll use partial sorting which will reduce the load while maintaing the Usability



In [ ]:
partial_sort_indexes = np.argpartition(total_votes_array,4)
print(partial_sort_indexes) # bottom four cloud platforms (The first four)
cloud_2023_partially_sorted = [cloud_2023_array[i] for i in partial_sort_indexes[:4]]
print("The bottom four cloud platforms are (least->less)\n",cloud_2023_partially_sorted)

[21 20 19 18 17  5  6  7  8 10 11  4 12 13 14 15 16  9  2  3  1 22  0]
The bottom four cloud platforms are (least->less)
 ['Colocation', 'Scaleway', 'IBM Cloud Or Watson', 'OpenStack']
